### ISSUE TITLE
Should this be an R package?

### ISSUE THREAD

**Issue by Aariq** [njtierney/demo-geotargets#3]
I think you mentioned in the targets discussion forum that it would be nice to have a spatial targets package as part of the "[Targetopia](https://wlandau.github.io/targetopia/packages.html)".  I'm working on a project that is using `targets` with geospatial data so I'd be happy to contribute to a package rather than keep all my solutions to myself.  Just a thought!

**Comment by njtierney** [comment]
Yeah I'm keen to make a geospatial targets targetopia package!

What shall we call it? Some ideas:

- geotargets
- spatialtargets
- targetspatial

I think I like geotargets the most.

**Comment by njtierney** [comment]
I made a discussion topic here: https://github.com/ropensci/targets/discussions/1248

**Comment by brownag** [comment]
+1 for geotargets. I'd be interested in contributing more to this effort where I can!

**Comment by adamhsparks** [comment]
+1 for {geotargets} as well.

**Comment by njtierney** [comment]
done! https://github.com/njtierney/geotargets
